apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hive-docker 
spec:
  selector:
    matchLabels:
      labels:
        app: hive-docker
    spec:
      containers:
        - name: hive-docker
          image: ghcr.io/abecker7/hivebox/abecker7/hive-docker:0.2.6
          imagePullPolicy: IfNotPresent
          ports: 
            - name: http
              containerPort: 5050
              protocol: TCP
