apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-account.yml
  - 00-role.yml
  - 01-role-binding.yml
  - 02-traefik-services.yml
  - 02-traefik.yml
  - 03-hive-services.yml
  - 04-hive-ingress.yml
