apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
spec:
  containers:
  - name: elasticsearch
    image: elastic/elasticsearch:8.16.5
    ports:
    - containerPort: 9200
---
apiVersion: v1
kind: Pod
metadata:
  name: logstash
spec:
  containers:
  - name: logstash
    image: elastic/logstash:8.16.5
    ports:
    - containerPort: 5044
    - containerPort: 9600 
---
apiVersion: v1
kind: Pod
metadata:
  name: kibana
spec:
  containers:
  - name: kibana
    image: elastic/kibana:8.16.5
    ports:
    - containerPort: 5601 
