apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec: 
  image: ghcr.io/stefanprodan/podinfo
  interval: 1m
--- 
metadata:
  name: hive
  namespace: flux-system
spec:
  image: ghcr.io/abecker7/hivebox/abecker7/hive-docker 
  interval: 1m
