apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata: 
  name: podinfo
  namespace: flux-system
spec: 
  imageRepositoryRef:
    name: podinfo
  policy:
    semver: 
      range: ">=5.0.0"
--- 
metadata:
  name: hive
    namespace: flux-system
spec:
  imageRepositoryRef:
    name: hive
  policy:
    semver:
      range: ">=0.3.0"
